name: Deploy API to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" 

      - name: Build
        # Added the extra folder level here
        run: dotnet build backend/Notes.Api/Notes.Api.csproj --configuration Release

      - name: Publish
        # Added the extra folder level here
        run: dotnet publish backend/Notes.Api/Notes.Api.csproj -c Release -o ./output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./output # This stays the same because -o ./output puts it in the root of the runner

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: api
          path: ./output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: buckeye-api-linhn
          package: ./output
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}